fail_fast: true
repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.260'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black     

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
     - id: check-added-large-files
     - id: check-toml
     - id: pretty-format-json
     - id: check-vcs-permalinks
     - id: detect-private-key

